version: '3'
services:

  nginx:
    image: nginx:1-alpine
    depends_on:
      - wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  wordpress:
    image: wordpress:php7.2-fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_DEBUG: "true"
    volumes:
      - wordpress:/var/www/html
      - ./data/wp-content:/var/www/html/wp-content
      - .:/var/www/html/${WORDPRESS_THEME}
      - .:/var/www/html/wp-content/themes/${WORDPRESS_THEME}

  cli:
    image: wordpress:cli
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - ./data/wp-content:/var/www/html/wp-content
      - .:/var/www/html/${WORDPRESS_THEME}
      - .:/var/www/html/wp-content/themes/${WORDPRESS_THEME}
    command: >
      sh /var/www/html/wp-content/themes/${WORDPRESS_THEME}/bin/wait-for.sh mysql:3306 -t 60 -- sh /var/www/html/wp-content/themes/${WORDPRESS_THEME}/bin/install.sh

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  wordpress:
    driver: local
  mysql:
    driver: local
